-- Create users table
create table public.users (
  id bigint generated by default as identity primary key,
  spotify_id text unique not null,
  display_name text,
  profile_image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create game_sessions table
create table public.game_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) not null,
  score integer not null,
  eaten_songs jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
